# Install packages and libraries needed to execute this code

# install.packages("tidyverse")
# install.packages('dplyr')
# install.packages("reshape2")
# install.packages('factoextra')
# install.packages("ggpubr")
# # install.packages('BiocManager')
# install.packages("plot3D")
# install.packages("VennDiagram")
# install.packages("santoku")
# instal.packages("ggforce")
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("DESeq2")
BiocManager::install("apeglm")
# install.packages('ggExtra')
# install.packages('RColorBrewer')

library(BiocManager)
library(ggplot2)
library(ggExtra)
library(RColorBrewer)
library(pheatmap)
library(readr)
library(DESeq2)
library(ggpubr)
library(stats)
library(MASS)
library(plot3D)
library(VennDiagram)

library(tidyverse)
library(tidyr)
library(apeglm)
library(santoku)
library(ggforce)

library(dplyr)
library(RColorBrewer)
library(SummarizedExperiment)

